Output demo/underscore-methods-usage-statistics.gif

Require underscore-methods-usage-statistics

Set Shell "bash"
Set Framerate 60
Set FontSize 12
Set Width 800
Set Height 400
Set Padding 20
Set Margin 5
Set MarginFill "#212830"
Set BorderRadius 10

Hide
Type 'cd /tmp/underscore-methods-usage-statistics-demo && clear' Enter
Show

Type "underscore-methods-usage-statistics --help" Sleep 200ms Enter
Wait Sleep 1500ms

Enter Enter Type "# scan a directory and count Underscore.js method usage" Sleep 200ms Enter Enter
Wait Sleep 800ms

Type "underscore-methods-usage-statistics ." Sleep 500ms Enter
Wait Sleep 2000ms

Sleep 3s
